#! /usr/bin/env python

"""
1 K = 8.6173324E-5 eV
1 eV = 1/8.6173324E-5 K
"""

import argparse

parser = argparse.ArgumentParser()

parser.add_argument('ev', type=float)
parser.add_argument('-i', '--inverse', action='store_true', default=False)

args = parser.parse_args()

K = 1/8.6173324E-5

if not args.inverse:
    ev = args.ev
    print '%10.3f eV = %10.2f K' % (ev, ev*K)

if args.inverse:
    kelvin = args.ev
    print '%10.3f K = %10.3f eV' % (kelvin, kelvin/K)
