#! /bin/bash

if [ "$*" ]; then
    files=$*
else
    files=vasp.out
fi

#Extract the number of ions from vasp.out
nions="`grep ' ions' vasp.out | awk '{print $7}'`"
#echo $nions

echo $files
> temp.tmp
for f in $files; do
    #grep F= $f | awk '{print $3}' >> temp.tmp
    #Corrected temperatures (T=TEBEG*NIONS/(NIONS-1))
    #grep F= $f | awk '{print $3}'| awk '{  s=($1!=0)?"-" {print ($1*$nions)/($nions-1);} else print $1; }'  >> temp.tmp
    grep F= $f | awk '{print $3}' | awk  '{  if ($1!=0) print $1; else print ($1*$nions)/($nions-1); } '  >> temp.tmp

    echo >> temp.tmp
done
xmgrace temp.tmp&
#rm temp.tmp
