#! /usr/bin/env python

import ase.io
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--poscar', default='POSCAR')

    args = parser.parse_args()

    fposcar = args.poscar

    atoms = ase.io.read(fposcar, format='vasp')

    for atom in atoms: 
        index = atom.index
        x, y, z = atom.x, atom.y, atom.z
        symbol = atom.symbol

        print '%2.2i  %2s %8.4f %8.4f %8.4f' % (index, symbol, x, y, z)
