#! /usr/bin/env python

import sys
import matplotlib.pyplot as plt
import numpy as np

fdimcar = 'DIMCAR'

try:
    step, force, torque, energy, curvature, angle = np.loadtxt(fdimcar, unpack=True, skiprows=1)
except ValueError:
    step, force, torque, energy, curvature, angle = np.genfromtxt(fdimcar, unpack=True, skip_header=1, skip_footer=1)


fig = plt.figure()
ax = fig.add_subplot(411)
bx = fig.add_subplot(412)
cx = fig.add_subplot(413)
dx = fig.add_subplot(414)

xmin, xmax = [0, max(step)]

ax.plot(step, np.log10(force), label='Log10(Force)')
ymin, ymax = [-2, 1]
ax.legend()
ax.grid()
ax.axis([xmin, xmax, ymin, ymax])

bx.plot(step, curvature, label='Curvature')
ymin, ymax = [-10, 10]
bx.legend()
bx.grid()
bx.axis([xmin, xmax, ymin, ymax])

cx.plot(step, angle, label='Angle')
ymin, ymax = [0, 2]
cx.legend()
cx.grid()
cx.axis([xmin, xmax, ymin, ymax])

dx.plot(step, energy, label='Energy')
vgap = 20e-3
ymin, ymax = [min(energy)-vgap, max(energy)+vgap]
dx.legend()
dx.grid()
dx.axis([xmin, xmax, ymin, ymax])

plt.show()
