#! /usr/bin/env python

import ase
from ase.io import vasp
import ase.lattice.spacegroup
from ase.calculators.vasp import Vasp

# Make the crystal
a = 3.2494; c = 5.2038
crys = ase.lattice.spacegroup.crystal('ZnO', [(1/3., 2/3., 0.), (1/3., 2/3., 0.3821)], spacegroup=186, cellpar=[a,a,c,90,90,120])

# Set the encut, kpoints and XC
encut = 400.
kpoints = (12,12,6)
gamma = True
xc = 'PBE'

# Set up the calculation parameters
calculator = Vasp(prec = 'Normal',
                encut = encut,
                lreal = 'Auto',
                ismear = 1,
                sigma = 0.1,
                kpts = kpoints,
                isif = 7,
                ibrion = 2,
                nsw = 40,
                xc = xc,
                gamma = gamma
                )

# Attach the calculator
crys.set_calculator(calculator)

# Write out the input files
calculator.initialize(crys)
vasp.write_vasp('POSCAR', calculator.atoms_sorted, symbol_count = calculator.symbol_count, direct=True, sort=True)
calculator.write_incar(crys)
calculator.write_kpoints()
calculator.write_potcar()
open('ready', 'w')
