#! /usr/bin/env python

import ase.io
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('n', nargs=3, type=int, default=[1,1,1])
    parser.add_argument('infile', default='POSCAR')
    parser.add_argument('outfile', default='POSCAR.supercell.vasp')

    args = parser.parse_args()

    atoms = ase.io.read(args.infile, format='vasp')
    supercell = atoms*tuple(args.n)
    ase.io.write(args.outfile, supercell, format='vasp', vasp5=True, direct=True, sort=True)
