#! /usr/bin/env python

import sys

fposcars = sys.argv[1:]

for fposcar in fposcars:
    lines = open(fposcar).readlines()
    line0 = lines[0]
    lines = lines[:5] + [line0] + lines[5:]
    newposcar = ''.join(lines).strip()
    open(fposcar, 'w').write(newposcar)
