#! /bin/bash

if [ "$*" ]; then
    files=$*
else
    files=vasp.out
fi

#Extract the number of ions from vasp.out
nions="`grep ' ions' vasp.out | awk '{print $7}'`"
#echo $nions

echo $files
> temp.tmp
for f in $files; do
    #grep F= $f | awk '{print $3}' >> temp.tmp
    #Corrected temperatures (T=TEBEG*NIONS/(NIONS-1))
    grep F= $f | awk '{print $3}'| awk '{ print ($1*$nions)/($nions-1)}'  >> temp.tmp

    echo >> temp.tmp
done
#xmgrace temp.tmp&
#rm temp.tmp

echo $files
> mag.tmp
for f in $files; do
    #grep F= $f | awk '{if ($17 <0) {print -$17} else {print $17}}' >> mag.tmp
    grep F= $f | awk '{print $17}' >> mag.tmp
    echo >> mag.tmp
done
#xmgrace mag.tmp&
#rm mag.tmp
echo $files
> cpu.tmp
for f in $files; do
    #grep F= $f | awk '{if ($17 <0) {print -$17} else {print $17}}' >> mag.tmp
    grep "LOOP+" $f | awk '{print $7}' >> cpu.tmp
    echo >> cpu.tmp
done
#xmgrace cpu.tmp&
#rm mag.tmp
