#! /usr/bin/env python

import sys
import ase.io
from ase.io import vasp
from ase.calculators.vasp import Vasp

file = sys.argv[1]
atoms = ase.io.read(file)
calc = Vasp(xc='PBE')
calc.initialize(atoms)
vasp.write_vasp('POSCAR.new', calc.atoms_sorted, symbol_count=calc.symbol_count)
