#! /usr/bin/env python

import os
import incar
import vaspcopy
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
            description = 'Setup convergence calculations for elastic tensor')

    parser.add_argument('-i', '--initial_encut', type=int, required=True)
    parser.add_argument('-f', '--final_encut', type=int)

    args = parser.parse_args()

    encut = args.initial_encut
    encuts = [encut]

    if args.final_encut:
        i = 1
        while encuts[-1] < args.final_encut:
            tmp = round(encut*(1+i*0.15))
            encuts.append(int(tmp))
            i += 1
    else:
        encuts.append(int(encut*1.10))
        encuts.append(int(encut*1.20))
        encuts.append(int(encut*1.30))

    print 'Using ENCUTS:', encuts
    print
    for encut in encuts:
        dir = 'encut_'+str(encut)
        print 'Creating directory %s' % (dir)
        os.mkdir(dir)
        src_dir = '.'
        dst_dir = dir
        vaspcopy.copy_start(src_dir, dst_dir)
        print 'Setting ENCUT to %i' % (encut)
        fincar = os.path.join(dir, 'INCAR')
        incar.incar().read(fincar).settag('encut = '+str(encut)).write(fincar)
        print
