#! /usr/bin/env python

# Executes the same command in all the directories given as input

import argparse
import subprocess as sp
import os

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--dirs', help='list of directories in which the \
command has to be executed', required=True, nargs='*')
    parser.add_argument('-c', '--command', help='command that needs to be \
executed', required=True)
    parser.add_argument('-rs', '--recsep', help='record separator to be used',
            default='\n', nargs='?')

    args = parser.parse_args()

    pwd = os.getcwd()
    #print args.dirs
    #print args.command
    for d in args.dirs:
        os.chdir(os.path.join(pwd, d))
        out = sp.check_output(args.command, shell=True)
        s = args.recsep.join([d, out.strip()])
        print s
