#! /bin/bash

if [ $1 ]; then
    f=$1
else
    f='POTCAR'
fi

echo $f
grep '^  PAW' -A1 $f
grep TITEL $f

version_test=$(grep -q 'mkinetic' $f)

if [ "$?" -eq 0 ]; then
    echo 'new version'
else
    echo 'old version'
fi
