#! /bin/bash

potim=`grep -i potim INCAR | awk -F = '{print $2}'`
grep 'g(F)' vasp.out | awk -F = '{print $3,$4,$5}' | awk '{if ($1+$3>$5) print "g(F)+g(S) > ort not good"; else print "good"}'
echo 'present potim:'$potim
grep trialstep vasp.out | awk '{print $NF}' | sed -e s/\)//g | awk '{printf "optimal potim: %4.2f\n", $potim*0.1}'
