#! /bin/bash

if [ "$*" ]; then
    files=$*
else
    files=vasp.out
fi

echo $files
> mag.tmp
for f in $files; do
    #grep F= $f | awk '{if ($17 <0) {print -$17} else {print $17}}' >> mag.tmp
    grep F= $f | awk '{print $17}' >> mag.tmp
    echo >> mag.tmp
done
xmgrace mag.tmp&
#rm mag.tmp
