#! /usr/bin/env python


#PBS -l nodes=1:ppn=2

import os,sys
pwd = os.environ['PBS_O_WORKDIR']
sys.path.append(pwd)
os.chdir(pwd)
import vaspsequencedevel
cmd = os.popen('/usr/bin/modulecmd python load vasp/5.2.12')
exec(cmd)
#os.system('which vasp')
vaspsequencedevel.execute('steps.yaml')
